name: newsforg_b2b_portal
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^15.1.1
  data_table_2: ^2.5.10   
  lucide_icons: ^0.257.0
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/fonts/bitter/
    - assets/fonts/merriweather/

  fonts:
    - family: Bitter
      fonts:
        - asset: assets/fonts/bitter/Bitter-VariableFont_wght.ttf
        - asset: assets/fonts/bitter/Bitter-Italic-VariableFont_wght.ttf
          style: italic

    - family: Merriweather
      fonts:
        - asset: assets/fonts/merriweather/Merriweather-VariableFont_opsz,wdth,wght.ttf
        - asset: assets/fonts/merriweather/Merriweather-Italic-VariableFont_opsz,wdth,wght.ttf
          style: italic

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
